USE [master]
GO

/****** Object:  Database [TjHrEvaluation]    Script Date: 01/07/2013 15:33:18 ******/
CREATE DATABASE [TjHrEvaluation] ON  PRIMARY 
( NAME = N'Database', FILENAME = N'E:\vs_projects\web\c01\App_Data\Database.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Database_log', FILENAME = N'E:\vs_projects\web\c01\App_Data\Database_log.ldf' , SIZE = 504KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
GO

ALTER DATABASE [TjHrEvaluation] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TjHrEvaluation].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TjHrEvaluation] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET ARITHABORT OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [TjHrEvaluation] SET AUTO_SHRINK ON 
GO

ALTER DATABASE [TjHrEvaluation] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TjHrEvaluation] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TjHrEvaluation] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TjHrEvaluation] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TjHrEvaluation] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TjHrEvaluation] SET  READ_WRITE 
GO

ALTER DATABASE [TjHrEvaluation] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TjHrEvaluation] SET  MULTI_USER 
GO

ALTER DATABASE [TjHrEvaluation] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TjHrEvaluation] SET DB_CHAINING OFF 
GO

